Padron/Controllers/FormController.cs
using Padron.Models;
using Padron.Models.PadronEntities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Padron.Controllers
{
    public class FormController : Controller
    {

        private ApplicationDbContext _context = new ApplicationDbContext();
        private PadronDbcontext _padronContext = new PadronDbcontext();
        // GET: Form
        public ActionResult Index()
        {
            return View();
        }

        // GET: Form/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        [Route("/Register")]
        public ActionResult Register()
        {

            //if (!_context.Users.Any(x => x.UserCode == id))
            //    throw new HttpException(404, "File Not Found");
            var model = new ContactForm();
            model.CascadingModel.Provincias = _context.Provincias.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();
            model.CascadingModel.ElectoralColleges = _context.ElectoralColleges.Select(x => new SelectListItem { Text = x.Codigo, Value = x.Codigo.ToString() }).ToList();
            model.CascadingModel.Users = _context.Users.Where(x => x.Activo == true && x.UserName != "admin").Select(x => new SelectListItem { Text = x.Nombres + " " + x.Apellidos, Value = x.Id.ToString() }).ToList();
            ModelState.Clear();

            return View(model);
        }

        [HttpGet]
        public ActionResult GetMunicipios(int provinciaId)
        {

            IEnumerable<SelectListItem> regions = _context.Municipios.Where(x => x.ProvinciaId == provinciaId)
            .Select(x => new SelectListItem { Text = x.Nombre, Value = x.Id.ToString() }).ToList();
            return Json(regions, JsonRequestBehavior.AllowGet);
        }

        //[HttpGet]
        //public ActionResult GetClients()
        //{

        //    //IEnumerable<SelectListItem> Client = _context.Clientes()
        //    //.Select(x => new SelectListItem { Text = x.Nombre, Value = x.Id.ToString() }).ToList();
        //    //return Json(Client, JsonRequestBehavior.AllowGet);
        //}

        [HttpGet]
        public ActionResult GetByCedula(string cedula)
        {
            cedula = cedula.Replace("-", "").Trim();
            var persona = _padronContext.Personas.FirstOrDefault(x => x.Cedula == cedula);
            return Json(persona  ?? new Persona(), JsonRequestBehavior.AllowGet);
        }




        public ActionResult Success()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register([Bind(Include = "Cedula,TelefonoMovil,FullName,ProvinciaId,MunicipioId,Sector,Email,IsInstagram,IsFacebook,IsTwitter,IsOther,ColaboradorDigitalRedes,Comentario,CoordinadorGuid,CascadingModel,Instagram,CodigoColegioElectoral,DistritoMunicipal,CoordinadorId")] ContactForm model)
        {
            model.CascadingModel.Provincias = _context.Provincias.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() }).ToList();

            ViewBag.IsSuccess = false;
            model.ConcatRedes();
            //var sd = Guid.Parse(Session["UserFormId"].ToString());
            //model.CoordinadorGuid = (model.CoordinadorGuid == Guid.Empty || model.CoordinadorGuid == null ? Guid.Parse(Session["UserFormId"].ToString()) : model.CoordinadorGuid);

            //ViewBag.UserFormId = model.CoordinadorGuid;
            var coordinador = _context.ContactForms.FirstOrDefault(x => x.Cedula == (model.Cedula.Replace("-", "").Trim()));
            if (coordinador != null)
            {
                ViewBag.Message = "Ya existe un elector con este numero de cedula!";
                model.CascadingModel.Users = _context.Users.Where(x => x.Activo == true && x.UserName != "admin").Select(x => new SelectListItem { Text = x.Nombres + " " + x.Apellidos, Value = x.Id.ToString() }).ToList();
                return View(model);
            }

            if (!ModelState.IsValid)
            {
                ViewBag.Message = String.Join(",",ModelState.Values.SelectMany(v => v.Errors).Select(x=>x.ErrorMessage));

                return View(model);
            }

            //model.CoordinadorId = coordinador.Id;
            model.Cedula = model.Cedula.Replace("-", "").Trim();

            _context.ContactForms.Add(model);
            _context.SaveChanges();
            ViewBag.IsSuccess = true;
            ViewBag.Message = "Registrado correctamente!";
            //model = new ContactForm();
            ModelState.Clear();

            return RedirectToAction("Success");
        }

            // GET: Form/Create
            public ActionResult Create()
        {
            return View();
        }

        // POST: Form/Create
        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: Form/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // GET: Form/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Form/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Padron/Views/Form/Register.cshtml
@model Padron.Models.ContactForm
@{
    ViewBag.Title = "#Registro de Electores";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

@*<h4 class="mx-auto">#Registro de Electores</h4>*@
@section styles{

    <style>
        #loading {
            display: none;
            position: fixed;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
            background: rgba(255,255,255,0.8);
            z-index: 1000;
        }

        #loadingcontent {
            display: table;
            position: fixed;
            left: 0;
            top: 0;
            width: 100%;
            height: 100%;
        }

        #loadingspinner {
            display: table-cell;
            vertical-align: middle;
            width: 100%;
            text-align: center;
            font-size: larger;
            padding-top: 80px;
        }
    </style>
}


    <div class="container">
        @if (ViewBag.IsSuccess != null)
        {
            <div class="row card-register mx-auto mt-5">
                <div class="col align-self-center">


                    @if (ViewBag.IsSuccess)
                    {
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>Información enviada correctamente!</strong>

                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        //Model = new Padron.Models.ContactForm();
                    }
                    else
                    {
                        <div class="alert alert-warning" role="alert">
                            @ViewBag.Message
                        </div>
                    }

                </div>
            </div>
        }

        <div id="loading">
            <div id="loadingcontent">
                <p id="loadingspinner">
                    Cargando...
                </p>
            </div>
        </div>

        @using (Html.BeginForm("Register", "Form", FormMethod.Post,new { id="contactForm", onsubmit="setLoading()" }))
        {
            @Html.AntiForgeryToken();
            @Html.ValidationSummary(true);
            <input type="hidden" value="@ViewBag.UserFormId" name="CoordinadorGuid" id="CoordinadorGuid" class="form-control" placeholder="CoordinadorGuid">
            <div class="card card-register mx-auto mt-5">



                <div class="card-header">#Registro de Electores</div>
                <div class="card-body">
                    <form>
                        <div class="form-group">
                            <div class="form-label-group">

                                @Html.DropDownListFor(m => m.CoordinadorId, (List<SelectListItem>)Model.CascadingModel.Users, "Selecciones un Multiplicador", new { @class = "form-control", id = "CoordinadorId" })

                                <span class="text-danger">@Html.ValidationMessageFor(m => m.CoordinadorId)</span>


                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group mb-3">
                                @Html.TextBoxFor(m => m.Cedula, new { @class = "form-control", @placeholder = "Cedula" })
                                @*<input value="@Model.Cedula" type="text" id="cedula" name="Cedula" class="form-control" placeholder="Cedula" autofocus="autofocus">*@
                                <div class="input-group-append">
                                    <button id="btnBuscarCedula" class="btn btn-secondary" type="button">Buscar</button>
                                </div>
                            </div>
                            <span class="text-danger">@Html.ValidationMessageFor(m => m.Cedula)</span>

                        </div>

                        <div class="form-group">
                            <div class="form-label-group">
                                @Html.TextBoxFor(m => m.FullName, new { @class = "form-control", @placeholder = "Nombre Completo" })
                                @*<input type="text" name="FullName" id="FullName" class="form-control" placeholder="Nombre Completo" required="required">*@
                                <label for="FullName">Nombre Completo</label>
                                <span class="text-danger">@Html.ValidationMessageFor(m => m.FullName)</span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-label-group">
                                @Html.TextBoxFor(m => m.TelefonoMovil, new { @class = "form-control", @placeholder = "Telefono" })

                                @*<input type="tel" name="TelefonoMovil" id="TelefonoMovil" class="form-control" placeholder="Telefono" required="required">*@
                                <label for="TelefonoMovil">Telefono</label>
                                <span class="text-danger">@Html.ValidationMessageFor(m => m.TelefonoMovil)</span>

                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-label-group">

                                @Html.DropDownListFor(m => m.ProvinciaId, (List<SelectListItem>)Model.CascadingModel.Provincias, "Selecciona una provincia", new { @class = "form-control", id = "ProvinciaId" })

                                @*<input type="tel" name="TelefonoMovil" id="TelefonoMovil" class="form-control" placeholder="Telefono" required="required">
                <label for="TelefonoMovil">Telefono</label>*@
                                <span class="text-danger">@Html.ValidationMessageFor(m => m.ProvinciaId)</span>


                            </div>
                        </div>

                        <div class="form-group">
                            <div class="form-label-group">
                                @*@Html.TextBoxFor(m => m.Municipio, new { @class = "form-control", @placeholder = "Municipio" })*@
                                @Html.DropDownListFor(m => m.MunicipioId, (List<SelectListItem>)Model.CascadingModel.Municipios, "Selecciona un municipio", new { @class = "form-control", @placeholder = "Municipio", id = "MunicipioId" })

                                @*<input type="text" name="Municipio" id="Municipio" class="form-control" placeholder="Municipio" required="required">*@
                                @*<label for="Municipio">Municipio</label>*@
                                <span class="text-danger">@Html.ValidationMessageFor(m => m.MunicipioId)</span>

                            </div>
                        </div>



                        <div class="form-group">
                            <div class="form-label-group">
                                @Html.TextBoxFor(m => m.Sector, new { @class = "form-control", @placeholder = "Sector" })

                                @*<input type="text" name="Sector" id="Sector" class="form-control" placeholder="Sector" required="required">*@
                                <label for="Sector">Sector</label>
                                <span class="text-danger">@Html.ValidationMessageFor(m => m.Sector)</span>

                                @*@Html.ValidationMessageFor(m => m.Sector)*@
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="form-label-group">
                                @*@Html.TextBoxFor(m => m.ColegioElectoral, new { @class = "form-control", @placeholder = "Colegio Electoral" })*@
                                @Html.DropDownListFor(m => m.CodigoColegioElectoral, (List<SelectListItem>)Model.CascadingModel.ElectoralColleges, "Seleccione su Colegio Electoral", new { @class = "form-control", id = "CodigoColegioElectoral" })

                                @*<input type="text" name="Email" id="Email" class="form-control" placeholder="Email" required="required">*@
                                @*<label for="Email">Colegio Electoral</label>*@
                                <span class="text-danger">@Html.ValidationMessageFor(m => m.CodigoColegioElectoral)</span>


                            </div>
                        </div>
                        <div class="form-group">
                            <div class="form-label-group">
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Email", @type = "email" })

                                @*<input type="text" name="Email" id="Email" class="form-control" placeholder="Email" required="required">*@
                                <label for="Email">Email</label>
                                <span class="text-danger">@Html.ValidationMessageFor(m => m.Email)</span>


                            </div>
                        </div>

                        <div class="form-group">
                            <div class="form-label-group">
                                @Html.TextBoxFor(m => m.Instagram, new { @class = "form-control", @placeholder = "Cuenta de Instagram" })
                                @*<input type="text" name="FullName" id="FullName" class="form-control" placeholder="Nombre Completo" required="required">*@
                                <label for="FullName">Cuenta de Instagram</label>
                                <span class="text-danger">@Html.ValidationMessageFor(m => m.Instagram)</span>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="form-label-group">
                                @Html.TextAreaFor(m => m.Comentario, new { @class = "form-control", @placeholder = "Comentario" })
                                @*<textarea type="text" name="Comentario" id="Comentario" class="form-control" placeholder="Comentario" required="required"></textarea>*@
                                @*<label for="Comentario">Comentario</label>*@
                                @Html.ValidationMessageFor(m => m.Comentario)
                            </div>
                        </div>
                        <input class="btn btn-primary btn-block" id="submitbtn" type="submit" value="Enviar" />
                        @*<a  href="login.html">Registrar</a>*@
                        <div>
                            @Html.ActionLink("Volver Al Menu", "../PersonasRegistradas/MisPersonas")
                        </div>
                    </form>
                </div>
            </div>
             
        }

    </div>




@section Scripts{

    <script src="~/Scripts/jquery.mask.js"></script>
    <script>
        $(document).ready(function () {
            $('#Cedula').mask('000-0000000-0');
            $('#TelefonoMovil').mask('000-000-0000');
            loadMunicipios();
        })

        function setLoading() {
            $("#loading").fadeIn();

        }



        $(function () {
            $('#ProvinciaId').change(function () {
                loadMunicipios();
            });

            $("#btnBuscarCedula").on('click', function () {
                var $txtCedula = $("#Cedula").val();
                var $txtNombres = $("#FullName");
                $("#loading").fadeIn();

                $.getJSON('@Url.Action("GetByCedula")', { cedula: $txtCedula }, function (persona) {
                    $("#loading").fadeOut();
                   
                    if (persona.Cedula) {
                        $txtNombres.val(persona.Nombre +" "+ persona.Apellido);
                    } else {
                        alert("Persona no encontrada");
                        $txtNombres.val("");
                    }
                })

            })
        })

        function loadMunicipios() {
        var selectedProvinciaId = $("#ProvinciaId").val();
        var municipiosSelect = $('#MunicipioId');
            municipiosSelect.empty();
            //municipiosSelect.append($('<option/>', {
            //    value: null,
            //    text: "Seleccione un municipio"
            //}));
                if (selectedProvinciaId != null && selectedProvinciaId != '') {
                    $.getJSON('@Url.Action("GetMunicipios")', { provinciaId: selectedProvinciaId }, function (municipios) {
                        if (municipios != null && !jQuery.isEmptyObject(municipios)) {
                            municipiosSelect.append($('<option/>', {
                                value: null,
                                text: "Seleccione un municipio"
                            }));
                            $.each(municipios, function (index, region) {
                                municipiosSelect.append($('<option/>', {
                                    value: region.Value,
                                    text: region.Text
                                }));
                            });
                        };
                    });
                }
        }
    </script>
}

Padron/Views/Form/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

<div id="w">
    <div id="content">
        <!-- Icons source http://dribbble.com/shots/913555-Flat-Web-Elements -->
        <div class="notify successbox">
            <h1>¡Elector Registrado, Exitosamente!</h1>
            <p>Muchas gracias por inscribirte, estaremos contactándote más adelante</p>

        </div>

        <div>
            @Html.ActionLink("Volver Al Menu", "../PersonasRegistradas/MisPersonas")
        </div>

        <div>
            @Html.ActionLink("Nuevo Registro", "Register")
        </div>

    </div><!-- @@end #content -->
</div><!-- @@end #w -->

@section styles{

    <style>
        /** resets **/
        html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, table, caption, tbody, tfoot, thead, tr, th, td, article, aside, canvas, details, embed, figure, figcaption, footer, header, hgroup, menu, nav, output, ruby, section, summary, time, mark, audio, video {
            margin: 0;
            padding: 0;
            border: 0;
            font-size: 100%;
            font: inherit;
            vertical-align: baseline;
            outline: none;
            -webkit-font-smoothing: antialiased;
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }

        html {
            height: 101%;
        }

        body {
            background: #f0f0f0 url('http://s22.postimg.org/3l1gnfmwd/image.gif');
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #313131;
            font-size: 62.5%;
            line-height: 1;
        }

        ::selection {
            background: #a4dcec;
        }

        ::-moz-selection {
            background: #a4dcec;
        }

        ::-webkit-selection {
            background: #a4dcec;
        }

        ::-webkit-input-placeholder { /* WebKit browsers */
            color: #ccc;
            font-style: italic;
        }

        :-moz-placeholder { /* Mozilla Firefox 4 to 18 */
            color: #ccc;
            font-style: italic;
        }

        ::-moz-placeholder { /* Mozilla Firefox 19+ */
            color: #ccc;
            font-style: italic;
        }

        :-ms-input-placeholder { /* Internet Explorer 10+ */
            color: #ccc !important;
            font-style: italic;
        }

        br {
            display: block;
            line-height: 2.2em;
        }

        article, aside, details, figcaption, figure, footer, header, hgroup, menu, nav, section {
            display: block;
        }

        ol, ul {
            list-style: none;
        }

        input, textarea {
            -webkit-font-smoothing: antialiased;
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            outline: none;
        }

        blockquote, q {
            quotes: none;
        }

            blockquote:before, blockquote:after, q:before, q:after {
                content: '';
                content: none;
            }

        strong {
            font-weight: bold;
        }

        table {
            border-collapse: collapse;
            border-spacing: 0;
        }

        img {
            border: 0;
            max-width: 100%;
        }

        #topbar {
            background: #4f4a41;
            padding: 10px 0 10px 0;
            text-align: center;
        }

            #topbar a {
                color: #fff;
                font-size: 1.3em;
                line-height: 1.25em;
                text-decoration: none;
                opacity: 0.5;
                font-weight: bold;
            }

                #topbar a:hover {
                    opacity: 1;
                }

        /** typography **/
        h1 {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 2.5em;
            line-height: 1.5em;
            letter-spacing: -0.05em;
            margin-bottom: 20px;
            padding: .1em 0;
            color: #444;
            position: relative;
            overflow: hidden;
            white-space: nowrap;
            text-align: center;
        }

            h1:before,
            h1:after {
                content: "";
                position: relative;
                display: inline-block;
                width: 50%;
                height: 1px;
                vertical-align: middle;
                background: #f0f0f0;
            }

            h1:before {
                left: -.5em;
                margin: 0 0 0 -50%;
            }

            h1:after {
                left: .5em;
                margin: 0 -50% 0 0;
            }

            h1 > span {
                display: inline-block;
                vertical-align: middle;
                white-space: normal;
            }

        p {
            display: block;
            font-size: 1.35em;
            line-height: 1.5em;
            margin-bottom: 22px;
        }


        /** page structure **/
        #w {
            display: block;
            width: 750px;
            margin: 0 auto;
            padding-top: 30px;
        }

        #content {
            display: block;
            width: 100%;
            background: #fff;
            padding: 25px 20px;
            padding-bottom: 35px;
            -webkit-box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 2px 0px;
            -moz-box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 2px 0px;
            box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 2px 0px;
        }


        .flatbtn {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            display: inline-block;
            outline: 0;
            border: 0;
            color: #f9f8ed;
            text-decoration: none;
            background-color: #b6a742;
            border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
            font-size: 1.2em;
            font-weight: bold;
            padding: 12px 22px 12px 22px;
            line-height: normal;
            text-align: center;
            vertical-align: middle;
            cursor: pointer;
            text-transform: uppercase;
            text-shadow: 0 1px 0 rgba(0,0,0,0.3);
            -webkit-border-radius: 3px;
            -moz-border-radius: 3px;
            border-radius: 3px;
            -webkit-box-shadow: 0 1px 0 rgba(15, 15, 15, 0.3);
            -moz-box-shadow: 0 1px 0 rgba(15, 15, 15, 0.3);
            box-shadow: 0 1px 0 rgba(15, 15, 15, 0.3);
        }

            .flatbtn:hover {
                color: #fff;
                background-color: #c4b237;
            }

            .flatbtn:active {
                -webkit-box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.1);
                -moz-box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.1);
                box-shadow: inset 0 1px 5px rgba(0, 0, 0, 0.1);
            }

        /** notifications **/
        .notify {
            display: block;
            background: #fff;
            padding: 12px 18px;
            max-width: 400px;
            margin: 0 auto;
            cursor: pointer;
            -webkit-border-radius: 3px;
            -moz-border-radius: 3px;
            border-radius: 3px;
            margin-bottom: 20px;
            box-shadow: rgba(0, 0, 0, 0.3) 0px 1px 2px 0px;
        }

            .notify h1 {
                margin-bottom: 6px;
            }

        .successbox h1 {
            color: #678361;
        }

        .errorbox h1 {
            color: #6f423b;
        }

        .successbox h1:before, .successbox h1:after {
            background: #cad8a9;
        }

        .errorbox h1:before, .errorbox h1:after {
            background: #d6b8b7;
        }

        .notify .alerticon {
            display: block;
            text-align: center;
            margin-bottom: 10px;
        }
    </style>
}